version: 0.2

env:
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
    STAGE: "dev"

phases:
  install:
    commands:
      - echo "Entered install phase..."
      - apt-get update && apt-get upgrade -y
      # Set up Node.js for Serverless
      - apt-get install -y build-essential
      - curl -sL https://deb.nodesource.com/setup_8.x | bash -
      - apt-get install -y nodejs
      # Set up pip, pipenv for Python project
      - python3 -m pip install pip awscli pipenv --upgrade
      - npm i && npm i -g serverless && pipenv install --dev
      # Set up DynamoDB local for testing
      - /usr/local/bin/dockerd-entrypoint.sh
      - docker image pull amazon/dynamodb-local
      - docker container run -p 8000:8000 -d amazon/dynamodb-local
    finally:
      - echo "Exited install phase..."
  pre_build:
    commands:
      - echo "Entered pre_build phase..."
      - pipenv run pytest tests/unit
    finally:
      - echo "Exited pre_build phase..."
  build:
    commands:
      - echo "Entered build phase..."
      - sls deploy --stage $STAGE | tee deploy-to-dev.out
    finally:
      - echo "Exited build phase..."
  post_build:
    commands:
      - echo "Entered post_build phase..."
      - pipenv run pytest tests/rest
    finally:
      - echo "Exited post_build phase..."
