# For complete reference:
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: Notes

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  parent: Stoic
  suite: Athena
  
  pythonRequirements:
    dockerizePip: true # For compiling 64-bit libraries
  
  stage: ${self:provider.stage}

  environments:
    dev: Dev
    test: Test
    prod: Prod
  
  domains:
    base: stoicapis.com
    prod: athena.${self:custom.domains.base}
    test: athena-test.${self:custom.domains.base}
    dev: athena-dev.${self:custom.domains.base}

  # Domain manager plugin settings:
  # https://github.com/amplify-education/serverless-domain-manager#known-issues
  customDomain:
    basePath: api
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRoute53Record: true
    certificateName: "*.${self:custom.domains.base}"

provider:
  name: aws
  runtime: python3.6
  
  # Note that VPC endpoint-enabled services should already have
  # their VPC endpoints created and associated with route tables & traffic 
  # related to the below subnets and security groups.
  vpc:
    securityGroupIds: # Must exist
      - sg-0af559c383b18a488
    subnetIds: # Must exist
      - subnet-39b83462
      - subnet-a64eb9c0
      - subnet-dfbdb496
  
  stackName: ${self:custom.parent}-${self:custom.suite}-${self:service}-${self:custom.environments.${self:provider.stage}}-Stack
  apiName: ${self:custom.parent}-${self:custom.suite}-${self:service}-${self:custom.environments.${self:provider.stage}}-Api

  stage: ${opt:stage, 'dev'}
  region: us-west-2
  
  stackTags: # Optional CloudFormation stack tags
    parent: ${self:custom.parent}
    suite: ${self:custom.suite}
    service: ${self:service}
  tags: # Optional service tags
    parent: ${self:custom.parent}
    suite: ${self:custom.suite}
    service: ${self:service}

  environment:
    DYNAMODB_TABLE: ${self:custom.parent}-${self:custom.suite}-${self:service}-${self:custom.environments.${self:provider.stage}}-Table
    DYNAMODB_HOST: https://dynamodb.${self:provider.region}.amazonaws.com
    DYNAMODB_GSI_USERID_NOTEID: ${self:custom.parent}-${self:custom.suite}-${self:service}-UserIdNoteId-${self:custom.environments.${self:provider.stage}}-Index
    DYNAMODB_GSI_NOTEBOOK_NOTEID: ${self:custom.parent}-${self:custom.suite}-${self:service}-NotebookNoteId-${self:custom.environments.${self:provider.stage}}-Index

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/${self:provider.environment.DYNAMODB_GSI_USERID_NOTEID}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/${self:provider.environment.DYNAMODB_GSI_NOTEBOOK_NOTEID}"

package:
  exclude:
    - .git/**
    - .idea/**
    - .vscode/**
    - .pytest_cache/**
    - tests/**

functions:
  create:
    handler: functions/handlers/create.create
    name: ${self:custom.parent}-${self:custom.suite}-${self:service}-Create-${self:custom.environments.${self:provider.stage}}-Func
    events:
      - http:
          path: notes
          method: post
          cors: true
    tags: # Optional function tags
      parent: ${self:custom.parent}
      suite: ${self:custom.suite}
      service: ${self:service}

  read:
    handler: functions/handlers/read.read
    name: ${self:custom.parent}-${self:custom.suite}-${self:service}-Read-${self:custom.environments.${self:provider.stage}}-Func
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
    tags: # Optional function tags
      parent: ${self:custom.parent}
      suite: ${self:custom.suite}
      service: ${self:service}

  update:
    handler: functions/handlers/update.update
    name: ${self:custom.parent}-${self:custom.suite}-${self:service}-Update-${self:custom.environments.${self:provider.stage}}-Func
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
    tags: # Optional function tags
      parent: ${self:custom.parent}
      suite: ${self:custom.suite}
      service: ${self:service}

  delete:
    handler: functions/handlers/delete.delete
    name: ${self:custom.parent}-${self:custom.suite}-${self:service}-Delete-${self:custom.environments.${self:provider.stage}}-Func
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
    tags: # Optional function tags
      parent: ${self:custom.parent}
      suite: ${self:custom.suite}
      service: ${self:service}

  searchByUser:
    handler: functions/handlers/search.search_by_user
    name: ${self:custom.parent}-${self:custom.suite}-${self:service}-SearchByUser-${self:custom.environments.${self:provider.stage}}-Func
    events:
      - http:
          path: users/{id}/notes
          method: get
          cors: true
    tags: # Optional function tags
      parent: ${self:custom.parent}
      suite: ${self:custom.suite}
      service: ${self:service}

  searchByNotebook:
    handler: functions/handlers/search.search_by_notebook
    name: ${self:custom.parent}-${self:custom.suite}-${self:service}-SearchByNotebook-${self:custom.environments.${self:provider.stage}}-Func
    events:
      - http:
          path: notebooks/{id}/notes
          method: get
          cors: true
    tags: # Optional function tags
      parent: ${self:custom.parent}
      suite: ${self:custom.suite}
      service: ${self:service}


# Schema based on:
# https://stackoverflow.com/questions/47289226/dynamodb-partition-key-choice-for-notes-app

# Read Capacity:
# (ITEM SIZE (rounded up to the next 4KB multiplier) / 4KB) * # of items
# (Round up to the nearest 4 KB multiplier)

# Write Capacity
# (ITEM SIZE (rounded up to the next 1KB multiplier) / 1KB) * # of items
# (Round up to the nearest 1 KB multiplier)
resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: noteId
            AttributeType: S # String
          - AttributeName: userId
            AttributeType: S # String
          - AttributeName: notebook
            AttributeType: S # String
        KeySchema:
          - AttributeName: noteId
            KeyType: HASH # Partition key
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          # To get all notes for a specified user.
          - IndexName: ${self:provider.environment.DYNAMODB_GSI_USERID_NOTEID}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH # Partition key
              - AttributeName: noteId
                KeyType: RANGE # Sort key
            Projection:
              NonKeyAttributes:
                - text
                - notebook
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          # To get all notes of a specified notebook.
          - IndexName: ${self:provider.environment.DYNAMODB_GSI_NOTEBOOK_NOTEID}
            KeySchema:
              - AttributeName: notebook
                KeyType: HASH # Partition key
              - AttributeName: noteId
                KeyType: RANGE # Sort key
            Projection:
              NonKeyAttributes:
                - userId
                - text
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
